### ISSUE TITLE
Recognize shell aliases 

### ISSUE THREAD

**Issue by AriaMoradi** [salman-abedin/devour#3]
```bash
$("$@") > /dev/null 2>&1
```
doesn't recognize shell aliases 
how about this?
```bash
SHELL=$(awk -F: -v user=$USER '$1 == user {print $NF}' /etc/passwd)
echo "$@" | $SHELL -i 
```

**Comment by AriaMoradi** [comment]
and about `-i`, all POSIX compliant shells should have it so it's safe and portable

**Comment by salman-abedin** [comment]
Frankly, even though that's a great feature, I need devour to be as fast as possible as this is literally the thing that launches stuff.
In fact, that's why I've kept the script as minimal as humanly possible.
Running a program like awk (or any other for no dire reason) before each launch is surely gonna slow it down.
But if enough people want this feature, I am willing to build it into the script so I'm gonna leave this issue open.
It's not like everyone is so broke as me and runs crappy machines. lol.

**Comment by AriaMoradi** [comment]
this has problems if there are spaces in path names

**Comment by salman-abedin** [comment]
Surely that can be easily handled if the need arises for this to be merged.

**Comment by taladar** [comment]
I don't see the use-case where you want to hide one terminal per command but where the delay of a single awk call would matter. It is not as if you do that in a tight loop.

**Comment by salman-abedin** [comment]
lol. Maybe you are right and It's just my autism. I'll see what I can do to merge this successfully. No promises though. =)

**Comment by salman-abedin** [comment]
All done. Adding  AriaMoradi as a contributor.
