### ISSUE TITLE
Don't devour when the command doesn't create a window

### ISSUE THREAD

**Issue by RaafatTurki** [salman-abedin/devour#5]
to use devour to its maximum potential one would alias it as such
```sh
swallow=devour
alias vlc="$swallow vlc"
alias sxiv="$swallow sxiv"
alias zathura="$swallow zathura"
alias mpv="$swallow mpv"
alias feh="$swallow feh"
```
however doing it as such would cause an unwanted behavior when no window is generated by the command, so it would simply devour the terminal and set it back effectively clearing it and the text generated by the command

If this is too much of a hassle at least don't devour when obvious things like `-h` and `--help` are given as command arguments

**Comment by salman-abedin** [comment]
I can easily put a few lines to guard that, but l've kept the script terse for a good reason.
It is basically a launcher script so any extra code is only gonna slow it down and that's gonna matter a lot.
I figured since it is a case based script, people are gonna use it only in the right condition like for an external program.
I have pet peeves about unnecessary codes and bloats. lol. 
fyi, if you really wanna take it to the next level, use a file browser like lf and script it into it.
Check out my demo.
I never call it from the terminal.
Instead, it is scripted into my file browser and thus it gives what I call the "True devouring experience"
Like DT, said in his review, no one launches stuff from their terminal and he is right.
This is why this was never meant to be used like that in the first place.
I thought people would take the hint from my demo as I showed how it's best used.
